return {
	kind = {
		Text = "",
		Method = "",
		Function = "",
		Constructor = "#",
		Field = "",
		Variable = "",
		Class = "𝓒",
		Interface = "⦿",
		Module = "",
		Property = "",
		Unit = "ﮭ",
		Value = "",
		Enum = "ℰ",
		Keyword = "",
		Snippet = "",
		Color = "",
		File = "",
		Reference = "",
		Folder = "",
		EnumMember = "",
		Constant = "",
		Struct = "𝓢",
		Event = "ﳅ",
		Operator = "",
		TypeParameter = "",
		Misc = "",
		Namespace = "",
		Null = "Null",
		Container = '⛶',
	},
	type = {
		Array = "",
		Number = "",
		String = "𝓐 ",
		Boolean = "",
		Object = "",
		Null = {icon = "NULL", hl = "TSType"},
	},
	documents = {
		File = "",
		Files = "",
		Folder = "",
		OpenFolder = "ﱮ",
	},
	git = {
		-- Add = "",
		-- Mod = "",
		-- Rename = "",
		-- Diff = "繁",
		-- Repo = "",

		Unstaged=     "",
		Staged=       "",
		Unmerged=     "",
		Renamed=      "ﱯ",
		Untracked=    "",
		Deleted=      "",
	},
	ui = {
		Lock = "",
		Circle = "",
		BigCircle = "ﭜ",
		BigUnfilledCircle = "",
		Close = "",
		NewFile = "",
		Search = "",
		Lightbulb = "",
		Project = "",
		Dashboard = "﵁",
		History = "",
		Comment = "",
		Bug = "",
		Code = "",
		Telescope = "",
		Gear = "",
		Package = "",
		List = "",
		SignIn = "",
		Check = "",
		Fire = "",
		Note = "ﴬ",
		BookMark = "",
		Pencil = "פֿ",
		ChevronRight = "",
		Table = "",
		Calendar = "",
	},
	diagnostics = {
		Error = "",
		Warning = "",
		Information = "",
		Question = "",
		Hint = "",
	},
	misc = {
		Robot = "ﮧ",
		Squirrel = "",
		-- Tag = "",
		Tag = "炙",
		Watch = " 慠",
	},

   folder= {
     -- arrow_open=   "",
     -- arrow_closed= "",
     arrow_open=   "",
     arrow_closed= "",
     default=      "",
     open=         "",
     empty=        "",
     empty_open=   "",
     symlink=      "",
     symlink_open= "",
    },
    arrows = {
      left = '',
    }
}
